### ISSUE TITLE
Order status not updated with error "No order found with 'somePurchaseId'"

### ISSUE THREAD

**Issue by oskar-olaussen** [avarda-ab/Magento-2-Checkout-3-module#30]
We have come across an issue where some orders status don't update to "Processing" as configured. We have also noticed that when this happen "No order found with 'somePurchaseId'" warning is logged.

This happens mainly with order's using directInvoice payment method, one case of zero amount being the exception. Note that this does not happen with ALL directInvoice payments.

Brief summary of what happens in my understanding:
1. While filling information on the checkout the quote gets an purchaseId. Let's call it "purchaseIdX".
2. While continuing to fill the information a second purchaseId is generated for the quote. Let's call it "purchaseIdY".
3. When the order is placed the "purchaseIdY" is saved for order in table avarda3_order_created.
4. When "/V1/avarda3/orderComplete" is called it is called with "purchaseIdX" => an order matching that purchaseId cannot be found in avarda3_order_created
5. The order status is not updated

We have discussed this issue with Avarda's support and their opinion was that the issue is not having multiple purchase ids but that order's cannot be found with them. Quote "Nuo tuplasessiot ovat sinänsä normaali asia, mutta outoa on se, että ne menevät Magentossa sekaisin"

Not sure if the support's understanding is correct? Should an order be found with ANY of the purchase ids related to the corresponding quote?

As this does not happen with all of the order's could it be related to in which order some calls are executed? Just guessing.

**Comment by juhanihaapala** [comment]
I've been trying to reproduce this issue since it was opened, now I finally got it. If you open checkout page in new tab and  you change postal code and then change shipping method it then triggers new purchase to avarda, but the tab left behind still has the old and if the purchase is finished there, then this error happens. There might and propably is other ways also to cause this.

I'll figure out how to fix and avoid this situation.
